# docker-compose.yml for local development

version: '3.5'

volumes:
  mysql:
    driver: 'local'

services:
  guardmech:
    build: ./
    env_file: .env-guardmech
    depends_on: ["mysql"]

  frontend:
    image: guardmech-frontend
    volumes:
      - "./coreui:/coreui"

  nginx:
    image: nginx
    ports:
      - "5001:80"
    volumes:
      - "./nginx.default.template:/etc/nginx/conf.d/default.template"
    env_file: .env-nginx
    command: /bin/bash -c "envsubst '$$NGINX_PORT $$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on: ["guardmech"]

  dumper_app:
    image: scalify/http-dump
    environment:
      - PORT=8080

  mysql:
    image: mysql:5.6
    volumes:
      - mysql:/var/lib/mysql
    env_file: .env-mysql
