# docker-compose.yml for local development

version: '3.5'

volumes:
  mysql:
    driver: 'local'

services:
  guardmech:
    build: ./
    env_file: .env-guardmech
    depends_on: ["mysql"]

  frontend:
    build: vue/
    volumes:
      - "./vue:/vue"

  oauth2_proxy:
    image: deweysasser/bitly-oauth2-proxy
    env_file: .env-oauth2proxy
    command: ["--upstream", "http://dummy:8080/", "--email-domain", "*", "-http-address", "0.0.0.0:4180", "-redirect-url", "http://localhost:5001/oauth2/callback", "-cookie-secure=false", "-set-xauthrequest"]

  nginx:
    image: nginx
    ports:
      - "5001:80"
    volumes:
      - "./nginx.default.template:/etc/nginx/conf.d/default.template"
    env_file: .env-nginx
    command: /bin/bash -c "envsubst '$$NGINX_PORT $$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on: ["guardmech"]

  dumper_app:
    image: scalify/http-dump
    environment:
      - PORT=8080

  mysql:
    image: mysql:5.6
    volumes:
      - mysql:/var/lib/mysql
    env_file: .env-mysql
