// Code generated by seacle.Generator DO NOT EDIT
// About seacle: https://github.com/acidlemon/seacle
package infra

import (
	"database/sql"

	"github.com/acidlemon/seacle"
	"github.com/google/uuid"
)

var _ seacle.Mappable = (*APIKey)(nil)

func (p *APIKey) Table() string {
	return "api_key"
}

func (p *APIKey) Columns() []string {
	return []string{"api_key.seq_id", "api_key.unique_id", "api_key.masked_token", "api_key.salt", "api_key.hashed_token", "api_key.principal_id"}
}

func (p *APIKey) PrimaryKeys() []string {
	return []string{"seq_id"}
}

func (p *APIKey) PrimaryValues() []interface{} {
	return []interface{}{p.SeqID}
}

func (p *APIKey) ValueColumns() []string {
	return []string{"unique_id", "masked_token", "salt", "hashed_token", "principal_id"}
}

func (p *APIKey) Values() []interface{} {
	return []interface{}{p.UniqueID, p.MaskedToken, p.Salt, p.HashedToken, p.PrincipalID}
}

func (p *APIKey) Scan(r seacle.RowScanner) error {
	var arg0 int64
	var arg1 uuid.UUID
	var arg2 string
	var arg3 string
	var arg4 string
	var arg5 int64

	err := r.Scan(&arg0, &arg1, &arg2, &arg3, &arg4, &arg5)
	if err == sql.ErrNoRows {
		return err
	} else if err != nil {
		// something wrong
		return err
	}

	p.SeqID = arg0
	p.UniqueID = arg1
	p.MaskedToken = arg2
	p.Salt = arg3
	p.HashedToken = arg4
	p.PrincipalID = arg5

	return nil
}
