// Code generated by seacle.Generator DO NOT EDIT
// About seacle: https://github.com/acidlemon/seacle
package infra

import (
	"database/sql"

	"github.com/acidlemon/seacle"
	"github.com/google/uuid"
)

var _ seacle.Mappable = (*Auth)(nil)

func (p *Auth) Table() string {
	return "auth"
}

func (p *Auth) Columns() []string {
	return []string{"auth.seq_id", "auth.unique_id", "auth.issuer", "auth.subject", "auth.email", "auth.principal_id"}
}

func (p *Auth) PrimaryKeys() []string {
	return []string{"seq_id"}
}

func (p *Auth) PrimaryValues() []interface{} {
	return []interface{}{p.SeqID}
}

func (p *Auth) ValueColumns() []string {
	return []string{"unique_id", "issuer", "subject", "email", "principal_id"}
}

func (p *Auth) Values() []interface{} {
	return []interface{}{p.UniqueID, p.Issuer, p.Subject, p.Email, p.PrincipalID}
}

func (p *Auth) Scan(r seacle.RowScanner) error {
	var arg0 int64
	var arg1 uuid.UUID
	var arg2 string
	var arg3 string
	var arg4 string
	var arg5 int64

	err := r.Scan(&arg0, &arg1, &arg2, &arg3, &arg4, &arg5)
	if err == sql.ErrNoRows {
		return err
	} else if err != nil {
		// something wrong
		return err
	}

	p.SeqID = arg0
	p.UniqueID = arg1
	p.Issuer = arg2
	p.Subject = arg3
	p.Email = arg4
	p.PrincipalID = arg5

	return nil
}
