// Code generated by seacle.Generator DO NOT EDIT
// About seacle: https://github.com/acidlemon/seacle
package infra

import (
	"database/sql"

	"github.com/acidlemon/seacle"
	"github.com/google/uuid"
)

var _ seacle.Mappable = (*Permission)(nil)

func (p *Permission) Table() string {
	return "permission"
}

func (p *Permission) Columns() []string {
	return []string{"permission.seq_id", "permission.unique_id", "permission.name", "permission.description"}
}

func (p *Permission) PrimaryKeys() []string {
	return []string{"seq_id"}
}

func (p *Permission) PrimaryValues() []interface{} {
	return []interface{}{p.SeqID}
}

func (p *Permission) ValueColumns() []string {
	return []string{"unique_id", "name", "description"}
}

func (p *Permission) Values() []interface{} {
	return []interface{}{p.UniqueID, p.Name, p.Description}
}

func (p *Permission) Scan(r seacle.RowScanner) error {
	var arg0 int64
	var arg1 uuid.UUID
	var arg2 string
	var arg3 string

	err := r.Scan(&arg0, &arg1, &arg2, &arg3)
	if err == sql.ErrNoRows {
		return err
	} else if err != nil {
		// something wrong
		return err
	}

	p.SeqID = arg0
	p.UniqueID = arg1
	p.Name = arg2
	p.Description = arg3

	return nil
}
