// Code generated by seacle.Generator DO NOT EDIT
// About seacle: https://github.com/acidlemon/seacle
package db

import (
	"database/sql"

	"github.com/acidlemon/seacle"
)

var _ seacle.Mappable = (*AuthOIDCRow)(nil)

func (p *AuthOIDCRow) Table() string {
	return "auth_oidc"
}

func (p *AuthOIDCRow) Columns() []string {
	return []string{"auth_oidc.seq_id", "auth_oidc.auth_oidc_id", "auth_oidc.issuer", "auth_oidc.subject", "auth_oidc.email", "auth_oidc.name", "auth_oidc.principal_seq_id"}
}

func (p *AuthOIDCRow) PrimaryKeys() []string {
	return []string{"seq_id"}
}

func (p *AuthOIDCRow) PrimaryValues() []interface{} {
	return []interface{}{p.SeqID}
}

func (p *AuthOIDCRow) ValueColumns() []string {
	return []string{"auth_oidc_id", "issuer", "subject", "email", "name", "principal_seq_id"}
}

func (p *AuthOIDCRow) Values() []interface{} {
	return []interface{}{p.AuthOIDCID, p.Issuer, p.Subject, p.Email, p.Name, p.PrincipalID}
}

func (p *AuthOIDCRow) Scan(r seacle.RowScanner) error {
	var arg0 int64
	var arg1 string
	var arg2 string
	var arg3 string
	var arg4 string
	var arg5 string
	var arg6 int64

	err := r.Scan(&arg0, &arg1, &arg2, &arg3, &arg4, &arg5, &arg6)
	if err == sql.ErrNoRows {
		return err
	} else if err != nil {
		// something wrong
		return err
	}

	p.SeqID = arg0
	p.AuthOIDCID = arg1
	p.Issuer = arg2
	p.Subject = arg3
	p.Email = arg4
	p.Name = arg5
	p.PrincipalID = arg6

	return nil
}
