// Code generated by seacle.Generator DO NOT EDIT
// About seacle: https://github.com/acidlemon/seacle
package db

import (
	"database/sql"

	"github.com/acidlemon/seacle"
)

var _ seacle.Mappable = (*PermissionRow)(nil)

func (p *PermissionRow) Table() string {
	return "permission"
}

func (p *PermissionRow) Columns() []string {
	return []string{"permission.seq_id", "permission.permission_id", "permission.name", "permission.description"}
}

func (p *PermissionRow) PrimaryKeys() []string {
	return []string{"seq_id"}
}

func (p *PermissionRow) PrimaryValues() []interface{} {
	return []interface{}{p.SeqID}
}

func (p *PermissionRow) ValueColumns() []string {
	return []string{"permission_id", "name", "description"}
}

func (p *PermissionRow) Values() []interface{} {
	return []interface{}{p.PermissionID, p.Name, p.Description}
}

func (p *PermissionRow) AutoIncrementColumn() string {
	return "seq_id"
}

func (p *PermissionRow) Scan(r seacle.RowScanner) error {
	var arg0 int64
	var arg1 string
	var arg2 string
	var arg3 string

	err := r.Scan(&arg0, &arg1, &arg2, &arg3)
	if err == sql.ErrNoRows {
		return err
	} else if err != nil {
		// something wrong
		return err
	}

	p.SeqID = arg0
	p.PermissionID = arg1
	p.Name = arg2
	p.Description = arg3

	return nil
}
