// Code generated by seacle.Generator DO NOT EDIT
// About seacle: https://github.com/acidlemon/seacle
package db

import (
	"database/sql"

	"github.com/acidlemon/seacle"
)

var _ seacle.Mappable = (*PrincipalRow)(nil)

func (p *PrincipalRow) Table() string {
	return "principal"
}

func (p *PrincipalRow) Columns() []string {
	return []string{"principal.seq_id", "principal.principal_id", "principal.name", "principal.description"}
}

func (p *PrincipalRow) PrimaryKeys() []string {
	return []string{"seq_id"}
}

func (p *PrincipalRow) PrimaryValues() []interface{} {
	return []interface{}{p.SeqID}
}

func (p *PrincipalRow) ValueColumns() []string {
	return []string{"principal_id", "name", "description"}
}

func (p *PrincipalRow) Values() []interface{} {
	return []interface{}{p.PrincipalID, p.Name, p.Description}
}

func (p *PrincipalRow) Scan(r seacle.RowScanner) error {
	var arg0 int64
	var arg1 string
	var arg2 string
	var arg3 string

	err := r.Scan(&arg0, &arg1, &arg2, &arg3)
	if err == sql.ErrNoRows {
		return err
	} else if err != nil {
		// something wrong
		return err
	}

	p.SeqID = arg0
	p.PrincipalID = arg1
	p.Name = arg2
	p.Description = arg3

	return nil
}
