// Code generated by seacle.Generator DO NOT EDIT
// About seacle: https://github.com/acidlemon/seacle
package db

import (
	"database/sql"

	"github.com/acidlemon/seacle"
)

var _ seacle.Mappable = (*RoleRow)(nil)

func (p *RoleRow) Table() string {
	return "role_info"
}

func (p *RoleRow) Columns() []string {
	return []string{"role_info.seq_id", "role_info.role_id", "role_info.name", "role_info.description"}
}

func (p *RoleRow) PrimaryKeys() []string {
	return []string{"seq_id"}
}

func (p *RoleRow) PrimaryValues() []interface{} {
	return []interface{}{p.SeqID}
}

func (p *RoleRow) ValueColumns() []string {
	return []string{"role_id", "name", "description"}
}

func (p *RoleRow) Values() []interface{} {
	return []interface{}{p.RoleID, p.Name, p.Description}
}

func (p *RoleRow) Scan(r seacle.RowScanner) error {
	var arg0 int64
	var arg1 string
	var arg2 string
	var arg3 string

	err := r.Scan(&arg0, &arg1, &arg2, &arg3)
	if err == sql.ErrNoRows {
		return err
	} else if err != nil {
		// something wrong
		return err
	}

	p.SeqID = arg0
	p.RoleID = arg1
	p.Name = arg2
	p.Description = arg3

	return nil
}
