name: "build-test"
on: [push]

defaults:
  run:
    working-directory: frontend

jobs:
  test_frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm install
    - id: test
      run: npm run type-check && npm run lint && npm run build