name: release

on:
  push:
    branches:
      - master
      - feature/build-*
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: docker login
        run: docker login ghcr.io -u acidlemon -p ${{ secrets.GITHUB_TOKEN }}
      - name: docker build
        run: docker build -t ghcr.io/${{ github.repository }}:$(git describe --tags) .
      - name: docker push
        run: docker push ghcr.io/${{ github.repository }}:$(git describe --tags)
