// Code generated by seacle.Generator DO NOT EDIT
// About seacle: https://github.com/acidlemon/seacle
package db

import (
	"database/sql"

	"github.com/acidlemon/seacle"
)

var _ seacle.Mappable = (*GroupRoleMapRow)(nil)

func (p *GroupRoleMapRow) Table() string {
	return "group_role_map"
}

func (p *GroupRoleMapRow) Columns() []string {
	return []string{"group_role_map.group_seq_id", "group_role_map.role_seq_id"}
}

func (p *GroupRoleMapRow) PrimaryKeys() []string {
	return []string{"group_seq_id", "role_seq_id"}
}

func (p *GroupRoleMapRow) PrimaryValues() []interface{} {
	return []interface{}{p.GroupSeqID, p.RoleSeqID}
}

func (p *GroupRoleMapRow) ValueColumns() []string {
	return []string{}
}

func (p *GroupRoleMapRow) Values() []interface{} {
	return []interface{}{}
}

func (p *GroupRoleMapRow) AutoIncrementColumn() string {
	return ""
}

func (p *GroupRoleMapRow) Scan(r seacle.RowScanner) error {
	var arg0 int64
	var arg1 int64

	err := r.Scan(&arg0, &arg1)
	if err == sql.ErrNoRows {
		return err
	} else if err != nil {
		// something wrong
		return err
	}

	p.GroupSeqID = arg0
	p.RoleSeqID = arg1

	return nil
}
