// Code generated by seacle.Generator DO NOT EDIT
// About seacle: https://github.com/acidlemon/seacle
package db

import (
	"database/sql"

	"github.com/acidlemon/seacle"
)

var _ seacle.Mappable = (*PrincipalRoleMapRow)(nil)

func (p *PrincipalRoleMapRow) Table() string {
	return "principal_role_map"
}

func (p *PrincipalRoleMapRow) Columns() []string {
	return []string{"principal_role_map.principal_seq_id", "principal_role_map.role_seq_id"}
}

func (p *PrincipalRoleMapRow) PrimaryKeys() []string {
	return []string{"principal_seq_id", "role_seq_id"}
}

func (p *PrincipalRoleMapRow) PrimaryValues() []interface{} {
	return []interface{}{p.PrincipalSeqID, p.RoleSeqID}
}

func (p *PrincipalRoleMapRow) ValueColumns() []string {
	return []string{}
}

func (p *PrincipalRoleMapRow) Values() []interface{} {
	return []interface{}{}
}

func (p *PrincipalRoleMapRow) AutoIncrementColumn() string {
	return ""
}

func (p *PrincipalRoleMapRow) Scan(r seacle.RowScanner) error {
	var arg0 int64
	var arg1 int64

	err := r.Scan(&arg0, &arg1)
	if err == sql.ErrNoRows {
		return err
	} else if err != nil {
		// something wrong
		return err
	}

	p.PrincipalSeqID = arg0
	p.RoleSeqID = arg1

	return nil
}
